/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RemoteCmdAgentImpl */

#ifndef _Included_RemoteCmdAgentImpl
#define _Included_RemoteCmdAgentImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef RemoteCmdAgentImpl_serialVersionUID
#define RemoteCmdAgentImpl_serialVersionUID -3215090123894869218LL
#undef RemoteCmdAgentImpl_serialVersionUID
#define RemoteCmdAgentImpl_serialVersionUID -4100238210092549637LL
#undef RemoteCmdAgentImpl_serialVersionUID
#define RemoteCmdAgentImpl_serialVersionUID 4974527148936298033LL
/*
 * Class:     RemoteCmdAgentImpl
 * Method:    C_GetLocalTime
 * Signature: (LRemoteInterface/GetLocalTime;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_RemoteCmdAgentImpl_C_1GetLocalTime
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
